#!/usr/bin/env bash
# run-mvp3-full-e2e.sh — OPS MVP-3 structured evidence E2E
#
# Produces: D:/tmp/e2e-out/run-<timestamp>-<id>/
#   profile-before.json / profile-app-down.json / profile-restored.json
#   verify-opsfix.log + verify-opsfix-result.json (generated by Python verifier)
#   round-NN/ (repair-result.json, lifecycle-events.ndjson, .attempts/, side-effect-result.json, cleanup-result.json)
#   overall-summary.json (generated by verify_evidence.py)
#
# After all rounds, runs verify_evidence.py for strict JSON validation and summary generation.

set -euo pipefail

ROUNDS="${1:-20}"
PYTHON="D:/Anaconda/python.exe"
SSH_KEY="$HOME/.ssh/id_ed25519_clawkit"
FIX_KEY="$HOME/.ssh/id_ed25519_clawkit_opsfix"
KNOWN="$HOME/.ssh/known_hosts"
REMOTE="122.51.51.118"
ROOT_SSH="ssh -i $SSH_KEY -o StrictHostKeyChecking=yes -o UserKnownHostsFile=$KNOWN -o BatchMode=yes -T root@${REMOTE}"
COMPOSE_DIR="/opt/clawkit/fixtures/postgres-lock"
COMPOSE_PROJECT="clawkit-ops-r6"
ENV_FILE="/etc/clawkit/ops-mcp.env"
ENV_BACKUP="/tmp/ops-mcp.env.bak.$$"
MVN_DIR="d:/Agent/miniclaw"
VERIFIER="d:/Agent/miniclaw/ops-fixtures/remote/verify_evidence.py"

opsro_mcp() {
    echo "$1" | ssh -i "$SSH_KEY" -o StrictHostKeyChecking=yes -o UserKnownHostsFile="$KNOWN" -o BatchMode=yes -o ConnectTimeout=5 -T "opsro@${REMOTE}" 2>/dev/null || echo '{}'
}

# ── Unique run directory (fail if exists) ──
RUN_TS=$(date -u +%Y%m%dT%H%M%SZ)
RANDID=$(od -A n -N 3 -t x1 /dev/urandom 2>/dev/null | tr -d ' \n' || echo $$)
RUN_ID="${RUN_TS}-${RANDID}"
OUTDIR="d:/tmp/e2e-out/run-${RUN_ID}"
if [[ -d "$OUTDIR" ]]; then
    echo "FATAL: run directory ${OUTDIR} already exists — refusing to overwrite"; exit 1
fi
mkdir "$OUTDIR" || { echo "FATAL: cannot create ${OUTDIR}"; exit 1; }
echo "Run directory: ${OUTDIR}"

VERIFY_OPSFIX_PASSED=false
PROFILE_SWITCH_PASSED=false
PROFILE_RESTORE_PASSED=false

cleanup() {
    echo ""; echo "=== CLEANUP ==="
    if $ROOT_SSH "test -f ${ENV_BACKUP}" 2>/dev/null; then
        $ROOT_SSH "cp ${ENV_BACKUP} ${ENV_FILE}" || true; sleep 1
        echo "  verifying restored profile via MCP..."
        { opsro_mcp '{"jsonrpc":"2.0","method":"initialize","id":1}'; echo '---TOOLS---'; opsro_mcp '{"jsonrpc":"2.0","method":"tools/list","id":2}'; } | \
          $PYTHON d:/Agent/miniclaw/ops-fixtures/remote/mcp_attest.py "$OUTDIR" restored --compare-before 2>&1 | tee "${OUTDIR}/.restore_match"
        if grep -q RESTORE_MATCH "${OUTDIR}/.restore_match" 2>/dev/null; then
            PROFILE_RESTORE_PASSED=true
            echo "  restore attestation: PASSED"
        else
            echo "  restore attestation: FAILED"
        fi
    fi
    $ROOT_SSH "rm -f /tmp/opsfix_test_key" 2>/dev/null || true

    # Run Python verifier for strict evidence validation and summary
    echo ""; echo "=== Evidence verifier ==="
    if $PYTHON "$VERIFIER" "$OUTDIR" "$ROUNDS" 2>&1; then
        echo "  verifier: PASSED"
    else
        echo "  verifier: FAILED (exit=$?)"
    fi
}

trap cleanup EXIT

# ── Pre-flight ──
echo "=== OPS MVP-3 Structured E2E (${ROUNDS} rounds) ==="
API_KEY="${CLAWKIT_API_KEY:-}"
[[ -z "$API_KEY" ]] && { echo "FATAL: CLAWKIT_API_KEY not set"; exit 1; }

# ── Profile attestation ──
echo ""; echo "=== Profile attestation ==="
echo "--- before ---"
{ opsro_mcp '{"jsonrpc":"2.0","method":"initialize","id":1}'; echo '---TOOLS---'; opsro_mcp '{"jsonrpc":"2.0","method":"tools/list","id":2}'; } | \
  $PYTHON d:/Agent/miniclaw/ops-fixtures/remote/mcp_attest.py "$OUTDIR" before 2>&1

$ROOT_SSH "cp ${ENV_FILE} ${ENV_BACKUP}" || { echo "FATAL: cannot backup env"; exit 1; }
$ROOT_SSH "sed -i 's/CLAWKIT_OPS_PROFILE=.*/CLAWKIT_OPS_PROFILE=APP_DOWN_V1/' ${ENV_FILE}"
sleep 1

echo "--- app-down ---"
{ opsro_mcp '{"jsonrpc":"2.0","method":"initialize","id":1}'; echo '---TOOLS---'; opsro_mcp '{"jsonrpc":"2.0","method":"tools/list","id":2}'; } | \
  $PYTHON d:/Agent/miniclaw/ops-fixtures/remote/mcp_attest.py "$OUTDIR" app-down 2>&1 | tee "${OUTDIR}/.switch_result"
if grep -q SWITCH_OK "${OUTDIR}/.switch_result" 2>/dev/null; then
    PROFILE_SWITCH_PASSED=true; echo "  switch: PASSED"
else
    echo "  switch: FAILED"; exit 1
fi

# ── Build ──
echo ""; echo "=== Build ==="
cd "$MVN_DIR"
mvn install -DskipTests -ntp -q || { echo "FATAL: build failed"; exit 1; }
echo "  build: OK"

# ── verify-opsfix ──
echo ""; echo "=== verify-opsfix ==="
VERIFY_OUT="${OUTDIR}/verify-opsfix.log"
scp -i "$SSH_KEY" -o StrictHostKeyChecking=yes -o UserKnownHostsFile="$KNOWN" -o BatchMode=yes \
  d:/Agent/miniclaw/ops-fixtures/remote/verify-opsfix.sh root@${REMOTE}:/tmp/ 2>/dev/null
scp -i "$SSH_KEY" -o StrictHostKeyChecking=yes -o UserKnownHostsFile="$KNOWN" -o BatchMode=yes \
  "$FIX_KEY" root@${REMOTE}:/tmp/opsfix_test_key 2>/dev/null
$ROOT_SSH "chmod 600 /tmp/opsfix_test_key; CLAWKIT_FIX_TEST_KEY=/tmp/opsfix_test_key bash /tmp/verify-opsfix.sh" > "$VERIFY_OUT" 2>&1
VERIFY_EXIT=$?
VERIFY_PASSES=$(grep -c '\[PASS\]' "$VERIFY_OUT" 2>/dev/null || true)
VERIFY_FAILS=$(grep -c '\[FAIL\]' "$VERIFY_OUT" 2>/dev/null || true)
# strip whitespace
VERIFY_PASSES=$(echo $VERIFY_PASSES | tr -d ' ')
VERIFY_FAILS=$(echo $VERIFY_FAILS | tr -d ' ')
echo "  verify: ${VERIFY_PASSES}P/${VERIFY_FAILS}F exit=${VERIFY_EXIT}"

# Block if verify fails: fail count must be 0 AND exit code must be 0
if [[ "$VERIFY_FAILS" != "0" || "$VERIFY_EXIT" != "0" ]]; then
    echo "FATAL: verify-opsfix failed — cannot start E2E rounds"; exit 1
fi
VERIFY_OPSFIX_PASSED=true

# ── Unauthorized side-effect test ──
echo ""; echo "=== Unauthorized side-effect test ==="
PRE_RESTART=$(opsro_mcp '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"container_status","arguments":{"service":"order-api"}},"id":1}' | $PYTHON -c "import json,sys; d=json.load(sys.stdin); sc=d.get('result',{}).get('structuredContent',{}); print(sc.get('data',{}).get('RestartCount',-1))" 2>/dev/null || echo "-1")
echo "  pre restart count: ${PRE_RESTART}"

# Send illegal request via opsfix
ILLEGAL_RESULT=$(echo '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"restart_service","arguments":{"serviceId":"postgres"}},"id":1}' | ssh -i "$FIX_KEY" -o StrictHostKeyChecking=yes -o UserKnownHostsFile="$KNOWN" -o BatchMode=yes -o ConnectTimeout=5 -T "opsfix@${REMOTE}" 2>/dev/null || echo '{}')
echo "  illegal result: $(echo "$ILLEGAL_RESULT" | grep -o '"message":"[^"]*"' | head -1)"
ILLEGAL_REJECTED=$(echo "$ILLEGAL_RESULT" | grep -c 'only serviceId=order-api' || true)

POST_RESTART=$(opsro_mcp '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"container_status","arguments":{"service":"order-api"}},"id":2}' | $PYTHON -c "import json,sys; d=json.load(sys.stdin); sc=d.get('result',{}).get('structuredContent',{}); print(sc.get('data',{}).get('RestartCount',-1))" 2>/dev/null || echo "-1")
echo "  post restart count: ${POST_RESTART}"

UNAUTHORIZED_SIDE_EFFECTS=0
if [[ "$PRE_RESTART" != "$POST_RESTART" ]]; then UNAUTHORIZED_SIDE_EFFECTS=1; fi
echo "  unauthorized side effects: ${UNAUTHORIZED_SIDE_EFFECTS}"

# Save result
$PYTHON -c "
import json
json.dump({
    'unauthorizedRequestsTested': 1,
    'unauthorizedRequestsRejected': ${ILLEGAL_REJECTED:-0},
    'unauthorizedSideEffects': ${UNAUTHORIZED_SIDE_EFFECTS},
    'passed': ${UNAUTHORIZED_SIDE_EFFECTS} == 0
}, open('${OUTDIR}/unauthorized-result.json','w'))
" 2>/dev/null

# ── Run rounds ──
echo ""
for ROUND in $(seq 1 "$ROUNDS"); do
    echo "=== Round ${ROUND}/${ROUNDS} ==="
    ROUND_OUT="${OUTDIR}/round-$(printf '%02d' "$ROUND")"
    mkdir "$ROUND_OUT"

    # Baseline
    $ROOT_SSH "docker compose --ansi never -f ${COMPOSE_DIR}/compose.yaml -p ${COMPOSE_PROJECT} up -d --wait order-api 2>/dev/null"; sleep 3
    SVC_CHECK=$(echo '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"service_status","arguments":{"service":"order-api"}},"id":1}' | opsro_mcp 2>/dev/null | grep -c '"State":"running"' || true)
    if [[ "$SVC_CHECK" -eq 0 ]]; then echo "  baseline: FAIL"; continue; fi
    echo "  baseline: OK"

    # Pre-repair RestartCount
    PRE_CTR=$(opsro_mcp '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"container_status","arguments":{"service":"order-api"}},"id":1}' | $PYTHON -c "import json,sys; d=json.load(sys.stdin); sc=d.get('result',{}).get('structuredContent',{}); print(sc.get('data',{}).get('RestartCount',-1))" 2>/dev/null || echo "-1")
    echo "  pre RestartCount: ${PRE_CTR}"

    # Inject APP_DOWN
    $ROOT_SSH "docker compose --ansi never -f ${COMPOSE_DIR}/compose.yaml -p ${COMPOSE_PROJECT} stop order-api 2>/dev/null"; sleep 1
    FAULT_CHECK=$(echo '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"service_status","arguments":{"service":"order-api"}},"id":1}' | opsro_mcp 2>/dev/null | grep -c '"State":"exited"' || true)
    echo "  fault: $( [[ "$FAULT_CHECK" -gt 0 ]] && echo confirmed || echo unconfirmed )"

    # Run Java pipeline
    cd "$MVN_DIR"
    set +e
    JAVA_STDOUT="${ROUND_OUT}/java-stdout.txt"
    JAVA_STDERR="${ROUND_OUT}/java-stderr.txt"
    CLAWKIT_REMOTE_OPS_HOST=${REMOTE} CLAWKIT_REMOTE_OPS_PORT=22 \
      CLAWKIT_REMOTE_OPS_USER=opsro \
      CLAWKIT_REMOTE_OPS_IDENTITY_FILE="$SSH_KEY" \
      CLAWKIT_REMOTE_OPS_KNOWN_HOSTS="$KNOWN" \
      CLAWKIT_REMOTE_OPS_EXPECTED_PROFILE=APP_DOWN_V1 \
      CLAWKIT_REMOTE_OPS_EXPECTED_PROBE_VERSION=1 \
      CLAWKIT_REMOTE_OPS_EXPECTED_TOOLSET_HASH=d822b006a5dcb84c \
      CLAWKIT_REMOTE_FIX_HOST=${REMOTE} CLAWKIT_REMOTE_FIX_USER=opsfix \
      CLAWKIT_REMOTE_FIX_IDENTITY_FILE="$FIX_KEY" \
      CLAWKIT_REMOTE_FIX_KNOWN_HOSTS="$KNOWN" \
      CLAWKIT_API_KEY="$API_KEY" \
      mvn exec:java -pl extensions/clawkit-ops-delivery \
        -Dexec.classpathScope=compile \
        -Dexec.mainClass="com.clawkit.ops.delivery.RemoteIncidentRepairMain" \
        -Dexec.args="--target r6 --output ${ROUND_OUT} --auto-approve" \
        -ntp > "$JAVA_STDOUT" 2> "$JAVA_STDERR"
    EXIT_CODE=$?
    set -e

    # Post-repair RestartCount
    POST_CTR=$(opsro_mcp '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"container_status","arguments":{"service":"order-api"}},"id":2}' | $PYTHON -c "import json,sys; d=json.load(sys.stdin); sc=d.get('result',{}).get('structuredContent',{}); print(sc.get('data',{}).get('RestartCount',-1))" 2>/dev/null || echo "-1")
    echo "  post RestartCount: ${POST_CTR}"

    # Side-effect result
    EXPECTED_RESTARTS=1
    OBSERVED=0
    if [[ "$PRE_CTR" != "-1" && "$POST_CTR" != "-1" ]]; then
        # Only count if exit code is 0 and restart actually happened
        if [[ "$EXIT_CODE" -eq 0 ]]; then
            OBSERVED=$((POST_CTR - PRE_CTR))
            if [[ "$OBSERVED" -lt 0 ]]; then OBSERVED=0; fi
        fi
    fi
    DUP_SFX=0
    if [[ "$OBSERVED" -gt "$EXPECTED_RESTARTS" ]]; then DUP_SFX=$((OBSERVED - EXPECTED_RESTARTS)); fi

    $PYTHON -c "
import json
json.dump({
    'measured': True,
    'serviceId': 'order-api',
    'before': {'RestartCount': ${PRE_CTR}},
    'after': {'RestartCount': ${POST_CTR}},
    'expectedRestarts': ${EXPECTED_RESTARTS},
    'observedRestarts': ${OBSERVED},
    'duplicateSideEffects': ${DUP_SFX},
    'passed': ${OBSERVED} == ${EXPECTED_RESTARTS} and ${DUP_SFX} == 0
}, open('${ROUND_OUT}/side-effect-result.json','w'))
" 2>/dev/null
    echo "  side-effect: expected=${EXPECTED_RESTARTS} observed=${OBSERVED} dup=${DUP_SFX}"

    # Result
    if [[ "$EXIT_CODE" -ne 0 ]]; then
        echo "  result: exit=${EXIT_CODE} (non-zero)"
    elif [[ -f "${ROUND_OUT}/repair-result.json" ]]; then
        STATE=$($PYTHON -c "import json; print(json.load(open('${ROUND_OUT}/repair-result.json')).get('attemptState','UNKNOWN'))" 2>/dev/null || echo "PARSE_ERROR")
        echo "  result: ${STATE}"
    else
        echo "  result: no repair-result.json"
    fi

    # Cleanup with real verification
    CLEAN_OK=false
    if $ROOT_SSH "docker compose --ansi never -f ${COMPOSE_DIR}/compose.yaml -p ${COMPOSE_PROJECT} up -d --wait order-api 2>/dev/null"; then
        sleep 3
        POST_SVC=$(echo '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"service_status","arguments":{"service":"order-api"}},"id":1}' | opsro_mcp 2>/dev/null | grep -c '"State":"running"' || true)
        POST_HTTP=$(echo '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"http_probe","arguments":{"endpoint":"order-api-metrics"}},"id":2}' | opsro_mcp 2>/dev/null | grep -c '"healthy":true' || true)
        if [[ "$POST_SVC" -gt 0 && "$POST_HTTP" -gt 0 ]]; then CLEAN_OK=true; fi
    fi
    $PYTHON -c "import json; json.dump({'passed': $CLEAN_OK}, open('${ROUND_OUT}/cleanup-result.json','w'))" 2>/dev/null
    echo "  cleanup: $( $CLEAN_OK && echo PASSED || echo FAILED )"
    echo ""
done

echo "=== All rounds complete ==="
