server {
    listen 80;
    server_name _;
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    location = /health {
        default_type application/json;
        return 200 '{"status":"UP","service":"demo-api"}';
    }

    location / {
        default_type application/json;
        return 200 '{"message":"demo-api"}';
    }
}
