upstream demo_api {
    server demo-api:80;
}

server {
    listen 80;
    server_name _;
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    location / {
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_pass http://demo_api;
    }
}
